### ISSUE TITLE
Bugs with Collision! Yaay

### ISSUE THREAD

**Issue by UgiNyaa** [htl22-3ahif/fun#17]
So, here we are. It is not easy to develop a valuable collision. This bug here is not that annoying, although i would like to make an issue about it, just to be known.

Before you really face the bug, you should know some details, which are essencial for this. So there is the type we are working with called float. He is inaccurate. So when working with small vectors (which happens when you have build in a gravitation), it can happen that float rounds it to make sure it fits in its 4 bytes. Because of that, the vector appreas longer then he accually is. So, if the rounding makes the vector longer, you glitch through walls.

But hey, I was exptected this kind of failure, so I build in a gap, to avoid that... but I was not smart enough... The gap serves for rounding the vector, so that it makes him smaller, not longer (little gap between boundingbox and the players positon (=point)). BUT it just could not be so easy. NO. Now i would like to explain you the problem with a visualisation:

![gap bug collision fun](https://cloud.githubusercontent.com/assets/16230790/12308268/ac8f4534-ba44-11e5-8343-83b2341c68fd.jpg)

As you can see, the player will never hold still, he will go up and down and up and down and up and down... (it is really annoying). Well, i did not expect that, but at least, I know where the bug is. This problem only exists, when there are small enough vectors, which can sneak through the gap. And this is the case in general gravitation.

I hope you have any ideas how to fix this. All suggestions would be appreciated.

**Comment by UgiNyaa** [comment]
First let me tell you, that all content above is not valid. It could theoretically happen, but it was not the cause of the problem we acually had.

The collision is calculating correctly, so the problem is not situated there. It was actually the order of updating the elements. As you can see in the xml data, i changed the order by putting the gravitationelement above collidinglement.
The gravitationelement is applying the gravitation, but the collidingelement had only the chance to correct it in the next frame. So there was one frame, where you were in the object you should not be. That is all. Nothing real special.

We just should analyse the problem more and better to work more efficient. I recommend to slow down the frame rate (see "thread.sleep(ms)" in "OnRenderFrame") as I did

**Comment by ghost** [comment]
Thank god we found the cause.
