### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by UgiNyaa** [htl22-3ahif/fun#18]
I would like to add support for the file format "JSON". It is similar to XML, but a bit easier to use. We also do not have enough knowledge to use XML properly. JSON should cover all we need.

I also was thinking about the structure, since it should define the whole environment with its entities and elements. So i got some concepts:
- My first idea was to write all informations in one json data. It would look like that:

``` json
{
  "Lib": "fun.Basics.dll",
  "Entities": [
  {
    "Name": "example",
    "Elements": [ { "Type": "TransformElement" } ] 
  },
  {
    "Name": "example2",
    "Elements": [
    { "Type": "TransformElement" },
    { "Type": "MeshElement " } ]
  }]
}
```
- The other idea was not to make it all in a data, but to put everithing in seperate data. Here an example:
  - environment (dir)
    - entity (dir)
      - TransformElement.json
    - entity (dir)
      - TransformElement.json
      - MeshElement.json

The json data contains other informations about the element. It is also more structured.

So what would you prefer?
Feel free to comment below.

**Comment by ghost** [comment]
I'd prefer the latter.

**Comment by UgiNyaa** [comment]
I think this is also invalid now, since we can not even develop the writer for xml
